(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else api.boot(root)})(typeof window!=='undefined'?window:this,function(){'use strict';
const STORAGE_KEY='yutoru_standard_app_v1';
const ACCESS={punch:['punch'],manager:['dashboard','staff','attendance','workSettings','transport','correction','export','devices','storeSettings'],accounting:['dashboard','attendance','payroll','paySettings','slips','history','export']};
const NAV={punch:[['punch','打刻']],manager:[['dashboard','概要'],['staff','スタッフ管理'],['attendance','勤怠'],['workSettings','勤務時間・手当'],['transport','交通費'],['correction','打刻修正'],['export','勤怠出力'],['devices','端末管理'],['storeSettings','店舗設定']],accounting:[['dashboard','概要'],['attendance','勤怠'],['payroll','給与計算'],['paySettings','給与設定'],['slips','給与明細'],['history','給与履歴'],['export','CSV・PDF出力']]};
const seed=()=>({schemaVersion:1,role:null,store:{name:'YUTORU DEMO STORE',earlyStart:'05:00',earlyEnd:'08:00',nightStart:'22:00',nightEnd:'05:00'},devices:{punch:1,manager:1,accounting:1},staff:[
 {id:'s1',name:'山田 太郎',rate:1500,overtimeRate:.25,earlyRate:.25,nightRate:.25,transport:600,other:12000},
 {id:'s2',name:'佐藤 花子',rate:1300,overtimeRate:.25,earlyRate:.25,nightRate:.25,transport:500,other:3000},
 {id:'s3',name:'鈴木 一郎',rate:1250,overtimeRate:.25,earlyRate:.25,nightRate:.25,transport:0,other:0},
 {id:'s4',name:'田中 美咲',rate:1400,overtimeRate:.25,earlyRate:.25,nightRate:.25,transport:null,other:5000}],attendance:[
 {id:1,staff:'s1',date:'2026-09-01',start:'09:00',end:'18:00',breakMin:60,transport:null},
 {id:2,staff:'s2',date:'2026-09-02',start:'09:00',end:'19:30',breakMin:60,transport:800},
 {id:3,staff:'s3',date:'2026-09-03',start:'05:00',end:'13:00',breakMin:45,transport:null},
 {id:4,staff:'s4',date:'2026-09-04',start:'18:00',end:'02:00',breakMin:60,transport:700},
 {id:5,staff:'s2',date:'2026-09-05',start:'22:00',end:'06:00',breakMin:0,transport:0}],punches:[],history:[]});
const mins=t=>{const [h,m]=t.split(':').map(Number);return h*60+m};
const overlap=(s,e,a,b)=>Math.max(0,Math.min(e,b)-Math.max(s,a));
function windowOverlap(start,end,from,to){let a=mins(from),b=mins(to);if(b<=a)b+=1440;return[-1440,0,1440].reduce((sum,shift)=>sum+overlap(start,end,a+shift,b+shift),0)}
function attendanceDetail(a,settings={earlyStart:'05:00',earlyEnd:'08:00',nightStart:'22:00',nightEnd:'05:00'}){let start=mins(a.start),end=mins(a.end);if(end<=start)end+=1440;const gross=end-start,work=Math.max(0,gross-a.breakMin);return{work,breakMin:a.breakMin,overtime:Math.max(0,work-480),early:windowOverlap(start,end,settings.earlyStart,settings.earlyEnd),night:windowOverlap(start,end,settings.nightStart,settings.nightEnd)}}
const fare=(a,s)=>a.transport===null||a.transport===undefined?(s.transport??0):a.transport;
function calculatePayroll(s,attendance,settings){const x=attendance.filter(a=>a.staff===s.id).reduce((r,a)=>{const d=attendanceDetail(a,settings);r.work+=d.work;r.overtime+=d.overtime;r.early+=d.early;r.night+=d.night;r.transport+=fare(a,s);return r},{work:0,overtime:0,early:0,night:0,transport:0});const base=x.work/60*s.rate,otPay=x.overtime/60*s.rate*s.overtimeRate,earlyPay=x.early/60*s.rate*s.earlyRate,nightPay=x.night/60*s.rate*s.nightRate;return{...x,base,otPay,earlyPay,nightPay,other:s.other,total:base+otPay+earlyPay+nightPay+x.transport+s.other}}
function authorize(role,page){return Boolean(ACCESS[role]&&ACCESS[role].includes(page))}
function snapshot(period,s,p){return{id:'pay-'+period+'-'+s.id,period,createdAt:new Date().toISOString(),staffId:s.id,staffName:s.name,storeName:'YUTORU DEMO STORE',settings:{rate:s.rate,overtimeRate:s.overtimeRate,earlyRate:s.earlyRate,nightRate:s.nightRate,other:s.other},result:{...p}}}
function csv(state){const rows=['日付,スタッフ名,出勤,退勤,休憩,実働,残業,早朝,深夜,交通費'];state.attendance.forEach(a=>{const s=state.staff.find(x=>x.id===a.staff),d=attendanceDetail(a,state.store);rows.push([a.date,s?.name||'削除済み',a.start,a.end,a.breakMin,d.work,d.overtime,d.early,d.night,fare(a,s||{})].join(','))});return '\ufeff'+rows.join('\n')}
function boot(w){const d=w.document,$=s=>d.querySelector(s),$$=s=>[...d.querySelectorAll(s)];let state=load();function load(){try{const x=JSON.parse(w.localStorage.getItem(STORAGE_KEY));return x?.schemaVersion===1?x:seed()}catch(_){return seed()}}function save(){w.localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),yen=x=>'¥'+Math.round(x).toLocaleString('ja-JP'),hours=x=>(x/60).toFixed(2)+'h',name=id=>state.staff.find(s=>s.id===id)?.name||'削除済み';
 function setRole(role){if(!ACCESS[role])return;state.role=role;save();$('#role-gate').classList.add('hidden');w.location.hash='#/'+role+'/'+ACCESS[role][0];render()}
 function route(){const [,requested,page]=w.location.hash.split('/');if(!state.role)return null;if(requested!==state.role||!authorize(state.role,page)){w.history.replaceState(null,'','#/'+state.role+'/'+ACCESS[state.role][0]);return{role:state.role,page:ACCESS[state.role][0]}}return{role:state.role,page}}
 function attendanceCards(edit){return state.attendance.map(a=>{const s=state.staff.find(x=>x.id===a.staff)||{},x=attendanceDetail(a,state.store);return`<article class="card work-card"><div class="row"><b>${a.date}　${esc(name(a.staff))}</b>${edit?`<button class="btn" data-att="${a.id}">修正</button>`:''}</div><dl><div><dt>勤務時間</dt><dd>${a.start}–${a.end}</dd></div><div><dt>休憩</dt><dd>${a.breakMin}分</dd></div><div><dt>実働</dt><dd>${hours(x.work)}</dd></div><div><dt>残業</dt><dd>${hours(x.overtime)}</dd></div><div><dt>早朝</dt><dd>${hours(x.early)}</dd></div><div><dt>深夜</dt><dd>${hours(x.night)}</dd></div><div><dt>交通費</dt><dd>${yen(fare(a,s))}</dd></div></dl></article>`}).join('')}
 const views={punch:()=>`<section class="card hero"><p class="eyebrow">打刻専用</p><h1>${esc(state.store.name)}</h1><p>本人の打刻操作だけを表示しています。給与情報にはアクセスできません。</p></section><section class="card"><h2>スタッフを選択</h2><select id="punch-staff">${state.staff.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select><div class="punch-actions" style="margin-top:12px">${['出勤','休憩開始','休憩終了','退勤'].map((x,i)=>`<button class="btn ${i===0?'btn-primary':i===3?'btn-danger':'btn-dark'}" data-punch="${x}">${x}</button>`).join('')}</div></section><section class="card"><div class="status-line"><h2>本日の勤務状況</h2><span class="status-pill">1分単位</span></div>${state.punches.slice(-8).reverse().map(p=>`<p>${esc(name(p.staff))}　<b>${p.type}</b> ${p.time}</p>`).join('')||'<p>まだ打刻はありません。</p>'}</section>`,
 dashboard:()=>`<section class="card hero"><p class="eyebrow">${state.role==='manager'?'MANAGER':'ACCOUNTING'}</p><h1>${state.role==='manager'?'店舗管理':'経理ダッシュボード'}</h1><p>${state.role==='manager'?'給与を表示せず、スタッフと勤怠を安全に管理します。':'全スタッフの勤怠・給与を確認します。'}</p></section><section class="grid"><div class="card metric"><small>スタッフ</small><b>${state.staff.length}名（無制限）</b></div><div class="card metric"><small>店舗ライセンス</small><b>1店舗</b></div></section>`,
 staff:()=>`<section class="card"><div class="row"><div><h1>スタッフ管理</h1><p>登録人数に上限はありません。</p></div><button class="btn btn-primary" id="add-staff">スタッフ登録</button></div>${state.staff.map(s=>`<div class="metric row"><b>${esc(s.name)}</b><button class="btn" data-staff="${s.id}">編集</button></div>`).join('')}</section>`,
 attendance:()=>`<section class="card"><div class="row"><div><h1>月間勤怠</h1><p>2026年9月</p></div>${state.role==='manager'?'<button class="btn btn-primary" id="add-att">勤怠追加</button>':''}</div><div class="desktop-table table-wrap"><table><thead><tr><th>日付</th><th>スタッフ名</th><th>勤務時間</th><th>休憩</th><th>実働</th><th>残業</th><th>早朝</th><th>深夜</th><th>交通費</th></tr></thead><tbody>${state.attendance.map(a=>{const s=state.staff.find(x=>x.id===a.staff)||{},x=attendanceDetail(a,state.store);return`<tr><td>${a.date}</td><td>${esc(name(a.staff))}</td><td>${a.start}–${a.end}</td><td>${a.breakMin}分</td><td>${hours(x.work)}</td><td>${hours(x.overtime)}</td><td>${hours(x.early)}</td><td>${hours(x.night)}</td><td>${yen(fare(a,s))}</td></tr>`}).join('')}</tbody></table></div></section><div class="mobile-list">${attendanceCards(state.role==='manager')}</div>`,
 workSettings:()=>`<section class="card"><h1>勤務時間・手当設定</h1><p>打刻は1分単位、残業は実働8時間超で計算します。</p><form id="work-form" class="form-grid"><label>早朝開始<input name="earlyStart" type="time" step="60" value="${state.store.earlyStart}"></label><label>早朝終了<input name="earlyEnd" type="time" step="60" value="${state.store.earlyEnd}"></label><label>深夜開始<input name="nightStart" type="time" step="60" value="${state.store.nightStart}"></label><label>深夜終了<input name="nightEnd" type="time" step="60" value="${state.store.nightEnd}"></label><button class="btn btn-primary">設定を保存</button></form><p class="notice">日跨ぎ勤務・休憩なし勤務に対応しています。</p></section>`,
 correction:()=>`<section class="card"><div class="row"><div><h1>打刻修正</h1><p>勤怠を1分単位で追加・修正できます。</p></div><button class="btn btn-primary" id="add-att">勤怠追加</button></div></section><div class="mobile-list" style="display:grid">${attendanceCards(true)}</div>`,
 devices:()=>`<section class="card"><h1>端末管理</h1><p class="notice">1店舗1ライセンスの端末枠です。</p><div class="setting-list"><div class="metric row"><b>打刻専用端末</b><span>${state.devices.punch}/1台</span></div><div class="metric row"><b>管理者端末</b><span>${state.devices.manager}/2台</span></div><div class="metric row"><b>経理端末</b><span>${state.devices.accounting}/1台</span></div></div></section>`,
 storeSettings:()=>`<section class="card"><h1>店舗設定</h1><form id="store-form" class="form-grid"><label>店舗名<input name="name" required value="${esc(state.store.name)}"></label><label>ライセンス<input disabled value="Standard／1店舗"></label><button class="btn btn-primary">店舗設定を保存</button></form></section>`,
 paySettings:()=>`<section class="card"><h1>給与設定</h1><p>給与は時給制のみです。スタッフごとに基本時給と各手当を設定します。</p>${state.staff.map(s=>`<div class="metric row"><div><b>${esc(s.name)}</b><small>基本時給 ${yen(s.rate)}</small></div><button class="btn" data-pay="${s.id}">設定</button></div>`).join('')}</section>`,
 slips:()=>`<section class="card"><h1>給与明細</h1><p>A4形式の給与明細を表示し、PDF保存または印刷できます。</p></section><div class="pay-list">${state.staff.map(s=>payCard(s)).join('')}</div>`,
 transport:()=>`<section class="card"><h1>交通費設定</h1><p class="notice">日別交通費がある日は通常交通費より優先します。「¥0」と未設定は別に保存します。</p>${state.staff.map(s=>`<div class="metric row"><div><b>${esc(s.name)}</b><small>通常交通費：${s.transport===null?'未設定':yen(s.transport)}</small></div><button class="btn" data-staff="${s.id}">設定</button></div>`).join('')}</section>`,
 payroll:()=>`<section class="card hero"><p class="eyebrow">PAYROLL</p><h1>給与・明細</h1><p>各割増は重複時間も項目ごとに根拠を表示します。</p></section><div class="pay-list">${state.staff.map(s=>payCard(s)).join('')}</div>`,
 history:()=>`<section class="card"><h1>給与履歴</h1><p>確定時点の設定と計算結果をスナップショット保存します。</p>${state.history.map(h=>`<article class="metric row"><div><small>${h.period}</small><b>${esc(h.staffName)}</b></div><b>${yen(h.result.total)}</b><button class="btn" data-history="${h.id}">明細</button></article>`).join('')||'<p>給与明細を確定すると履歴に保存されます。</p>'}</section>`,
 export:()=>`<section class="card"><h1>勤怠出力</h1><p>スマートフォンからCSV保存・PDF印刷を利用できます。</p><div class="actions"><button class="btn btn-primary" id="csv">CSV出力</button><button class="btn btn-dark" id="attendance-print">PDF／印刷表示</button></div></section>`};
 function payCard(s){const p=calculatePayroll(s,state.attendance,state.store);return`<article class="card pay-card"><div class="row"><h2>${esc(s.name)}</h2><b class="total">${yen(p.total)}</b></div><dl><div><dt>基本給与</dt><dd>${yen(p.base)}</dd></div><div><dt>残業手当</dt><dd>${yen(p.otPay)}</dd></div><div><dt>早朝手当</dt><dd>${yen(p.earlyPay)}</dd></div><div><dt>深夜手当</dt><dd>${yen(p.nightPay)}</dd></div><div><dt>その他手当</dt><dd>${yen(p.other)}</dd></div><div><dt>交通費</dt><dd>${yen(p.transport)}</dd></div></dl><div class="actions"><button class="btn" data-pay="${s.id}">給与設定</button><button class="btn btn-primary" data-slip="${s.id}">給与明細を見る</button></div></article>`}
 function render(){const r=route();if(!r)return;$('#role-switch').value=r.role;$('#nav').innerHTML=NAV[r.role].map(([p,n])=>`<button data-page="${p}" class="${p===r.page?'active':''}">${n}</button>`).join('');$('#app').innerHTML=views[r.page]();bind()}
 function open(html){$('#modal-content').innerHTML=html;$('#modal').showModal()}function closeButtons(){$$('[data-close]').forEach(b=>b.onclick=()=>$('#modal').close())}
 function staffForm(id){const current=state.staff.find(s=>s.id===id)||{id:'s'+Date.now(),name:'',rate:1200,overtimeRate:.25,earlyRate:.25,nightRate:.25,transport:null,other:0};open(`<h2>${id?'スタッフ・交通費編集':'スタッフ登録'}</h2><form id="staff-form" class="form-grid"><label>氏名<input name="name" required value="${esc(current.name)}"></label>${state.role==='manager'?`<label>通常交通費（空欄＝未設定）<input name="transport" type="number" min="0" value="${current.transport??''}"></label>`:''}<div class="actions"><button class="btn btn-primary">保存</button><button type="button" class="btn" data-close>閉じる</button></div></form>`);$('#staff-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);current.name=f.get('name');if(state.role==='manager')current.transport=f.get('transport')===''?null:Number(f.get('transport'));if(!id)state.staff.push(current);save();$('#modal').close();render()};closeButtons()}
 function attendanceForm(id){if(state.role!=='manager')return;const a=state.attendance.find(x=>x.id===id)||{id:Date.now(),staff:state.staff[0]?.id,date:'2026-09-11',start:'09:00',end:'18:00',breakMin:60,transport:null};open(`<h2>勤怠${id?'修正':'追加'}</h2><form id="att-form" class="form-grid"><label>スタッフ<select name="staff">${state.staff.map(s=>`<option value="${s.id}" ${s.id===a.staff?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label>日付<input name="date" type="date" value="${a.date}"></label><label>出勤<input name="start" type="time" step="60" value="${a.start}"></label><label>退勤<input name="end" type="time" step="60" value="${a.end}"></label><label>休憩（分）<input name="breakMin" type="number" min="0" value="${a.breakMin}"></label><label>日別交通費（空欄＝未設定）<input name="transport" type="number" min="0" value="${a.transport??''}"></label><div class="actions"><button class="btn btn-primary">保存</button><button type="button" class="btn" data-close>閉じる</button></div></form>`);$('#att-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);Object.assign(a,{staff:f.get('staff'),date:f.get('date'),start:f.get('start'),end:f.get('end'),breakMin:Number(f.get('breakMin')),transport:f.get('transport')===''?null:Number(f.get('transport'))});if(!id)state.attendance.push(a);save();$('#modal').close();render()};closeButtons()}
 function payForm(id){if(state.role!=='accounting')return;const s=state.staff.find(x=>x.id===id);open(`<h2>給与設定｜${esc(s.name)}</h2><form id="pay-form" class="form-grid"><label>基本時給<input name="rate" type="number" min="0" value="${s.rate}"></label><label>残業割増率（%）<input name="ot" type="number" value="${s.overtimeRate*100}"></label><label>早朝割増率（%）<input name="early" type="number" value="${s.earlyRate*100}"></label><label>深夜割増率（%）<input name="night" type="number" value="${s.nightRate*100}"></label><label>通常交通費（空欄＝未設定）<input name="transport" type="number" min="0" value="${s.transport??''}"></label><label>その他手当<input name="other" type="number" min="0" value="${s.other}"></label><div class="actions"><button class="btn btn-primary">保存</button><button type="button" class="btn" data-close>閉じる</button></div></form>`);$('#pay-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);Object.assign(s,{rate:Number(f.get('rate')),overtimeRate:Number(f.get('ot'))/100,earlyRate:Number(f.get('early'))/100,nightRate:Number(f.get('night'))/100,transport:f.get('transport')===''?null:Number(f.get('transport')),other:Number(f.get('other'))});save();$('#modal').close();render()};closeButtons()}
 function slip(s,p,record=true){if(state.role!=='accounting')return;if(record){const snap=snapshot('2026-09',s,p);const i=state.history.findIndex(x=>x.id===snap.id);if(i<0)state.history.unshift(snap);save()}open(`<article class="print-sheet"><header class="print-sheet__head"><p class="eyebrow">${esc(state.store.name)}</p><h1>給与明細書</h1><p>対象期間：2026年9月1日〜9月30日　<strong>${esc(s.name)} 様</strong></p></header><div class="grid"><div class="metric"><small>基本時給</small><b>${yen(s.rate)}</b></div><div class="metric"><small>実働時間</small><b>${hours(p.work)}</b></div><div class="metric"><small>基本給与</small><b>${yen(p.base)}</b></div><div class="metric"><small>残業時間／手当（${s.overtimeRate*100}%）</small><b>${hours(p.overtime)}／${yen(p.otPay)}</b></div><div class="metric"><small>早朝時間／手当（${s.earlyRate*100}%）</small><b>${hours(p.early)}／${yen(p.earlyPay)}</b></div><div class="metric"><small>深夜時間／手当（${s.nightRate*100}%）</small><b>${hours(p.night)}／${yen(p.nightPay)}</b></div><div class="metric"><small>その他手当</small><b>${yen(p.other)}</b></div><div class="metric"><small>交通費</small><b>${yen(p.transport)}</b></div><div class="metric"><small>支給合計</small><b class="total">${yen(p.total)}</b></div></div><p class="notice">デモ計算です。税・社会保険などの控除は含みません。</p></article><div class="actions no-print"><button class="btn btn-dark" id="print-slip">PDF保存／印刷</button><button class="btn" data-close>閉じる</button></div>`);$('#print-slip').onclick=()=>{d.body.classList.add('printing');w.print();d.body.classList.remove('printing')};closeButtons()}
 function bind(){const workForm=$('#work-form');if(workForm)workForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);Object.assign(state.store,{earlyStart:f.get('earlyStart'),earlyEnd:f.get('earlyEnd'),nightStart:f.get('nightStart'),nightEnd:f.get('nightEnd')});save();render()};const storeForm=$('#store-form');if(storeForm)storeForm.onsubmit=e=>{e.preventDefault();state.store.name=new FormData(e.target).get('name');save();render()};$$('#nav [data-page]').forEach(b=>b.onclick=()=>{w.location.hash='#/'+state.role+'/'+b.dataset.page});$$('[data-punch]').forEach(b=>b.onclick=()=>{state.punches.push({staff:$('#punch-staff').value,type:b.dataset.punch,time:new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})});save();render()});$('#add-staff')?.addEventListener('click',()=>staffForm());$('#add-att')?.addEventListener('click',()=>attendanceForm());$$('[data-att]').forEach(b=>b.onclick=()=>attendanceForm(Number(b.dataset.att)));$$('[data-staff]').forEach(b=>b.onclick=()=>staffForm(b.dataset.staff));$$('[data-pay]').forEach(b=>b.onclick=()=>payForm(b.dataset.pay));$$('[data-slip]').forEach(b=>b.onclick=()=>{const s=state.staff.find(x=>x.id===b.dataset.slip);slip(s,calculatePayroll(s,state.attendance,state.store))});$$('[data-history]').forEach(b=>b.onclick=()=>{const h=state.history.find(x=>x.id===b.dataset.history),s={...h.settings,name:h.staffName};slip(s,h.result,false)});$('#csv')?.addEventListener('click',()=>download(csv(state),'YUTORU_Standard_勤怠.csv','text/csv'));$('#attendance-print')?.addEventListener('click',()=>w.print())}
 function download(data,name,type){const a=d.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
 $$('[data-role]').forEach(b=>b.onclick=()=>setRole(b.dataset.role));$('#role-switch').onchange=e=>setRole(e.target.value);w.addEventListener('hashchange',render)}
return{STORAGE_KEY,ACCESS,seed,attendanceDetail,fare,calculatePayroll,authorize,snapshot,csv,boot};});
