(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else api.boot(root)})(typeof window!=='undefined'?window:this,function(){'use strict';
const STORAGE_KEY='yutoru_standard_app_v1';
const ACCESS={punch:['punch'],manager:['dashboard','staff','attendance','workSettings','transport','correction','export','devices','storeSettings'],accounting:['dashboard','attendance','payroll','paySettings','slips','history','export']};
const NAV={punch:[['punch','打刻']],manager:[['dashboard','概要'],['staff','スタッフ管理'],['attendance','勤怠'],['workSettings','勤務時間・手当'],['transport','交通費'],['correction','打刻修正'],['export','勤怠出力'],['devices','端末管理'],['storeSettings','店舗設定']],accounting:[['dashboard','概要'],['attendance','勤怠'],['payroll','給与計算'],['paySettings','給与設定'],['slips','給与明細'],['history','給与履歴'],['export','CSV・PDF出力']]};
const seed=()=>({schemaVersion:3,role:null,store:{name:'YUTORU DEMO STORE',earlyStart:'05:00',earlyEnd:'08:00',earlyHourlyAdd:200,nightStart:'22:00',nightEnd:'05:00',adminPin:'1234'},devices:{punch:1,manager:1,accounting:1},staff:[
 {id:'s1',name:'山田 太郎',rate:1500,overtimeRate:.25,earlyRate:.25,nightRate:.25,transport:600,other:12000},
 {id:'s2',name:'佐藤 花子',rate:1300,overtimeRate:.25,earlyRate:.25,nightRate:.25,transport:500,other:3000},
 {id:'s3',name:'鈴木 一郎',rate:1250,overtimeRate:.25,earlyRate:.25,nightRate:.25,transport:0,other:0},
 {id:'s4',name:'田中 美咲',rate:1400,overtimeRate:.25,earlyRate:.25,nightRate:.25,transport:null,other:5000}],attendance:[
 {id:1,staff:'s1',date:'2026-09-01',start:'10:35',end:'22:02',breakMin:113,transport:null},
 {id:2,staff:'s2',date:'2026-09-02',start:'08:17',end:'19:46',breakMin:67,transport:800},
 {id:3,staff:'s3',date:'2026-09-03',start:'05:13',end:'14:28',breakMin:52,transport:null},
 {id:4,staff:'s4',date:'2026-09-04',start:'18:37',end:'02:13',breakMin:41,transport:700},
 {id:5,staff:'s2',date:'2026-09-05',start:'21:43',end:'06:11',breakMin:37,transport:0},
 {id:6,staff:'s1',date:'2026-09-06',start:'23:58',end:'08:07',breakMin:49,transport:0},
 {id:7,staff:'s3',date:'2026-09-07',start:'13:01',end:'22:00',breakMin:60,transport:0},
 {id:8,staff:'s4',date:'2026-09-08',start:'13:01',end:'22:02',breakMin:60,transport:0},
 {id:9,staff:'s2',date:'2026-09-09',start:'21:59',end:'22:01',breakMin:0,transport:0}],punches:[],history:[]});
const mins=t=>{const [h,m]=t.split(':').map(Number);return h*60+m};
const overlap=(s,e,a,b)=>Math.max(0,Math.min(e,b)-Math.max(s,a));
function windowOverlap(start,end,from,to){let a=mins(from),b=mins(to);if(b<=a)b+=1440;return[-1440,0,1440].reduce((sum,shift)=>sum+overlap(start,end,a+shift,b+shift),0)}
function attendanceDetail(a,settings={earlyStart:'05:00',earlyEnd:'08:00',nightStart:'22:00',nightEnd:'05:00'}){let start=mins(a.start),end=mins(a.end);if(end<=start)end+=1440;const gross=end-start,work=Math.max(0,gross-a.breakMin);return{work,breakMin:a.breakMin,overtime:Math.max(0,work-480),early:windowOverlap(start,end,settings.earlyStart,settings.earlyEnd),night:windowOverlap(start,end,settings.nightStart,settings.nightEnd)}}
const fare=(a,s)=>a.transport===null||a.transport===undefined?(s.transport??0):a.transport;
function calculatePayroll(s,attendance,settings){const x=attendance.filter(a=>a.staff===s.id).reduce((r,a)=>{const d=attendanceDetail(a,settings);r.work+=d.work;r.overtime+=d.overtime;r.early+=d.early;r.night+=d.night;r.transport+=fare(a,s);return r},{work:0,overtime:0,early:0,night:0,transport:0});const base=Math.round(x.work/60*s.rate),otPay=Math.round(x.overtime/60*s.rate*s.overtimeRate),earlyPay=Math.round(x.early/60*(Number(settings.earlyHourlyAdd)||0)),nightPay=Math.round(x.night/60*s.rate*s.nightRate),transport=Math.round(x.transport),other=Math.round(s.other);return{...x,transport,base,otPay,earlyPay,nightPay,other,total:base+otPay+earlyPay+nightPay+transport+other}}
function authorize(role,page){return Boolean(ACCESS[role]&&ACCESS[role].includes(page))}
const requiresPin=role=>role==='manager'||role==='accounting';
const verifyPin=(role,pin,adminPin)=>!requiresPin(role)||String(pin)===String(adminPin);
function snapshot(period,s,p){return{id:'pay-'+period+'-'+s.id,period,createdAt:new Date().toISOString(),staffId:s.id,staffName:s.name,storeName:'YUTORU DEMO STORE',settings:{rate:s.rate,overtimeRate:s.overtimeRate,earlyHourlyAdd:Number(state?.store?.earlyHourlyAdd)||0,nightRate:s.nightRate,other:s.other},result:{...p}}}
function csv(state){const rows=['日付,スタッフ名,出勤,退勤,休憩,実働,残業,早朝,深夜,交通費'];state.attendance.forEach(a=>{const s=state.staff.find(x=>x.id===a.staff),d=attendanceDetail(a,state.store);rows.push([a.date,s?.name||'削除済み',a.start,a.end,a.breakMin,d.work,d.overtime,d.early,d.night,fare(a,s||{})].join(','))});return '\ufeff'+rows.join('\n')}
function boot(w){const d=w.document,$=s=>d.querySelector(s),qsa=s=>Array.from(d.querySelectorAll(s));let state=load(),selectedPunchStaff='';selectedPunchStaff=state.staff[0]?.id||'';function load(){try{const x=JSON.parse(w.localStorage.getItem(STORAGE_KEY));if(x?.schemaVersion===3){x.store=x.store||{};if(!x.store.adminPin)x.store.adminPin='1234';return x}return seed()}catch(_){return seed()}}function save(){w.localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),yen=x=>'¥'+Math.round(x).toLocaleString('ja-JP'),hours=x=>`${Math.floor(x/60)}:${String(x%60).padStart(2,'0')}`,name=id=>state.staff.find(s=>s.id===id)?.name||'削除済み';
 function printDocument(title,content){return`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>:root{--navy:#10233f;--line:#dce5e8;--muted:#62717d}*{box-sizing:border-box}html{font-size:16px}body{margin:0;padding:24px;background:#fff;color:var(--navy);font-family:-apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif}.sheet{width:min(100%,182mm);margin:0 auto}.document-head{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:24px;padding-bottom:14px;border-bottom:2px solid var(--navy)}.document-head h1,.document-head p{margin:3px 0}.document-head>div:last-child{text-align:right}.print-logo{font-size:24px;letter-spacing:.18em}.guide{margin:0 auto 24px;padding:10px 12px;border-radius:8px;background:#f3f6f8;color:var(--muted);font-size:12px;text-align:center}.slip-staff{display:flex;align-items:baseline;gap:28px;padding:10px 4px;border-bottom:1px solid var(--line)}.slip-staff span,.slip-details dt{color:var(--muted);font-size:13px}.slip-staff strong{font-size:21px}.slip-details{margin:0}.slip-details div{display:grid;grid-template-columns:1fr 1fr;align-items:center;min-height:52px;padding:8px 14px;border-bottom:1px solid var(--line)}.slip-details dd{margin:0;text-align:right;font-size:17px;font-weight:800}.slip-details .slip-total{margin-top:12px;border:0;background:var(--navy);color:#fff}.slip-details .slip-total dt{color:#fff;font-weight:800}.slip-details .slip-total dd{font-size:26px}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;white-space:nowrap}th,td{padding:9px 6px;border-bottom:1px solid var(--line);font-size:12px;text-align:right}th{background:#f7f9fa;color:#526270}th:first-child,td:first-child{text-align:left}@media(max-width:600px){body{padding:16px 10px}.document-head{display:block}.document-head>div:last-child{margin-top:14px;text-align:left}.print-logo{font-size:21px}.slip-details div{padding:8px 5px}.slip-details dd{font-size:15px}.table-wrap{overflow:visible}table{white-space:normal;table-layout:fixed}th,td{padding:6px 2px;font-size:9px;overflow-wrap:anywhere}}@page{size:A4 portrait;margin:14mm}@media print{body{padding:0}.guide{display:none}.sheet{width:100%}.document-head{margin-bottom:12px}thead{display:table-header-group}tr,.slip-details div{break-inside:avoid;page-break-inside:avoid}}</style></head><body><p class="guide">共有ボタンから“プリント”または“ファイルに保存”を選択してください</p><main class="sheet">${content}</main></body></html>`}
 function openPrintPage(title,content){const page=w.open('','_blank');if(!page){w.alert('印刷専用ページを開けませんでした。ポップアップを許可して、もう一度お試しください。');return false}try{page.document.open();page.document.write(printDocument(title,content));page.document.close();return true}catch(_){page.close();w.alert('印刷専用ページを表示できませんでした。もう一度お試しください。');return false}}
 function printHead(title){return`<header class="document-head"><div><b class="print-logo">YUTORU</b><p>${esc(state.store.name)}</p></div><div><h1>${title}</h1><p>対象期間：2026年9月1日〜9月30日</p></div></header>`}
 function payrollPrintContent(){return`${printHead('給与一覧')}<div class="table-wrap"><table><thead><tr><th>スタッフ名</th><th>基本給与</th><th>残業手当</th><th>早朝手当</th><th>深夜手当</th><th>その他手当</th><th>交通費</th><th>支給合計</th></tr></thead><tbody>${state.staff.map(s=>{const p=calculatePayroll(s,state.attendance,state.store);return`<tr><th scope="row">${esc(s.name)}</th><td>${yen(p.base)}</td><td>${yen(p.otPay)}</td><td>${yen(p.earlyPay)}</td><td>${yen(p.nightPay)}</td><td>${yen(p.other)}</td><td>${yen(p.transport)}</td><td><b>${yen(p.total)}</b></td></tr>`}).join('')}</tbody></table></div>`}
 function attendancePrintContent(){return`${printHead('勤怠一覧')}<div class="table-wrap"><table><thead><tr><th>日付</th><th>スタッフ名</th><th>勤務時間</th><th>休憩</th><th>実働</th><th>残業</th><th>早朝</th><th>深夜</th><th>交通費</th></tr></thead><tbody>${state.attendance.map(a=>{const s=state.staff.find(x=>x.id===a.staff)||{},x=attendanceDetail(a,state.store);return`<tr><td>${esc(a.date)}</td><td>${esc(name(a.staff))}</td><td>${esc(a.start)}–${esc(a.end)}</td><td>${a.breakMin}分</td><td>${hours(x.work)}</td><td>${hours(x.overtime)}</td><td>${hours(x.early)}</td><td>${hours(x.night)}</td><td>${yen(fare(a,s))}</td></tr>`}).join('')}</tbody></table></div>`}
 function fourUpSlip(s){const p=calculatePayroll(s,state.attendance,state.store);return`<article class="batch-slip"><header><b>YUTORU</b><span>給与明細書</span></header><p class="batch-period">2026年9月1日〜9月30日</p><h2>${esc(s.name)} 様</h2><dl><div><dt>基本時給</dt><dd>${yen(s.rate)}</dd></div><div><dt>実働時間</dt><dd>${hours(p.work)}</dd></div><div><dt>基本給与</dt><dd>${yen(p.base)}</dd></div><div><dt>残業手当</dt><dd>${yen(p.otPay)}</dd></div><div><dt>早朝手当</dt><dd>${yen(p.earlyPay)}</dd></div><div><dt>深夜手当</dt><dd>${yen(p.nightPay)}</dd></div><div><dt>その他手当</dt><dd>${yen(p.other)}</dd></div><div><dt>交通費</dt><dd>${yen(p.transport)}</dd></div><div class="batch-total"><dt>支給合計</dt><dd>${yen(p.total)}</dd></div></dl></article>`}
 function fourUpPrintDocument(){const pages=[];for(let i=0;i<state.staff.length;i+=4)pages.push(`<section class="batch-page" data-page="${pages.length+1}">${state.staff.slice(i,i+4).map(fourUpSlip).join('')}</section>`);return`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>給与明細 4人ずつ印刷</title><style>:root{--navy:#10233f;--line:#bfcbd0;--muted:#62717d}*{box-sizing:border-box}html,body{margin:0;background:#edf1f3;color:var(--navy);font-family:-apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif}.guide{margin:12px;text-align:center;font-size:12px}.batch-page{display:grid;grid-template-columns:repeat(2,1fr);grid-template-rows:repeat(2,1fr);gap:6mm;width:210mm;height:297mm;margin:12px auto;padding:10mm;background:white;break-after:page;page-break-after:always}.batch-page:last-child{break-after:auto;page-break-after:auto}.batch-slip{min-width:0;min-height:0;padding:5mm;border:1px solid var(--line);overflow:hidden;break-inside:avoid;page-break-inside:avoid}.batch-slip header{display:flex;justify-content:space-between;border-bottom:2px solid var(--navy);padding-bottom:2mm;font-size:11px}.batch-slip header b{letter-spacing:.12em}.batch-period{margin:2mm 0;color:var(--muted);font-size:8px;text-align:right}.batch-slip h2{margin:2mm 0;font-size:14px}.batch-slip dl{margin:0}.batch-slip dl div{display:grid;grid-template-columns:1fr 1fr;padding:1.4mm 0;border-bottom:1px solid var(--line);font-size:9px}.batch-slip dd{margin:0;text-align:right;font-weight:700}.batch-total{margin-top:2mm;padding:2mm!important;background:var(--navy);color:#fff;font-size:11px!important}@media(max-width:700px){.batch-page{grid-template-columns:1fr;grid-template-rows:none;width:100%;height:auto;margin:0;padding:10px;gap:10px}.batch-slip{padding:14px}.batch-slip dl div{padding:6px 0;font-size:12px}}@page{size:A4 portrait;margin:0}@media print{html,body{background:#fff}.guide{display:none}.batch-page{grid-template-columns:repeat(2,1fr);grid-template-rows:repeat(2,1fr);gap:6mm;width:210mm;height:297mm;padding:10mm;margin:0}.batch-slip{break-inside:avoid;page-break-inside:avoid}}</style></head><body><p class="guide">A4縦・2列×2段で、1ページに最大4人の給与明細を印刷します</p>${pages.join('')}</body></html>`}
 function openFourUpPrintPage(){const page=w.open('','_blank');if(!page){w.alert('印刷専用ページを開けませんでした。ポップアップを許可して、もう一度お試しください。');return false}page.document.open();page.document.write(fourUpPrintDocument());page.document.close();return true}
 function setRole(role){if(!ACCESS[role])return;state.role=role;save();$('#role-gate').classList.add('hidden');w.location.hash='#/'+role+'/'+ACCESS[role][0];render()}
 function requestRole(role){if(!ACCESS[role])return;if(!requiresPin(role)){setRole(role);return}open(`<h2>管理者PIN認証</h2><p>${role==='manager'?'オーナー・店長':'給与管理'}を開くにはPINを入力してください。</p><form id="pin-form" class="form-grid"><label>PIN<input name="pin" type="password" inputmode="numeric" pattern="[0-9]{4,8}" minlength="4" maxlength="8" autocomplete="current-password" required autofocus></label><p id="pin-error" class="notice hidden" role="alert">PINが正しくありません。</p><div class="actions"><button class="btn btn-primary">認証</button><button type="button" class="btn" data-close>閉じる</button></div></form>`);$('#pin-form').onsubmit=e=>{e.preventDefault();const pin=new FormData(e.target).get('pin');if(!verifyPin(role,pin,state.store.adminPin||'1234')){$('#pin-error').classList.remove('hidden');e.target.elements.pin.select();return}$('#modal').close();setRole(role)};closeButtons()}
 function route(){const [,requested,page]=w.location.hash.split('/');if(!state.role)return null;if(requested!==state.role||!authorize(state.role,page)){w.history.replaceState(null,'','#/'+state.role+'/'+ACCESS[state.role][0]);return{role:state.role,page:ACCESS[state.role][0]}}return{role:state.role,page}}
 function attendanceCards(edit){return state.attendance.map(a=>{const s=state.staff.find(x=>x.id===a.staff)||{},x=attendanceDetail(a,state.store);return`<article class="card work-card"><div class="row"><b>${a.date}　${esc(name(a.staff))}</b>${edit?`<button class="btn" data-att="${a.id}">修正</button>`:''}</div><dl><div><dt>勤務時間</dt><dd>${a.start}–${a.end}</dd></div><div><dt>休憩</dt><dd>${a.breakMin}分</dd></div><div><dt>実働</dt><dd>${hours(x.work)}</dd></div><div><dt>残業</dt><dd>${hours(x.overtime)}</dd></div><div><dt>早朝</dt><dd>${hours(x.early)}</dd></div><div><dt>深夜</dt><dd>${hours(x.night)}</dd></div><div><dt>交通費</dt><dd>${yen(fare(a,s))}</dd></div></dl></article>`}).join('')}
 function latestPunchFor(staffId){return [...state.punches].reverse().find(p=>p.staff===staffId)||null}
 function punchStatus(staffId){const p=latestPunchFor(staffId);if(!p||p.type==='退勤')return'off';if(p.type==='休憩開始')return'break';return'working'}
 function punchOptions(staffId){const status=punchStatus(staffId);if(status==='off')return[{type:'出勤',label:'出勤',tone:'primary',primary:true}];if(status==='break')return[{type:'休憩終了',label:'休憩終了',tone:'primary',primary:true}];return[{type:'休憩開始',label:'休憩開始',tone:'dark',primary:true},{type:'退勤',label:'退勤',tone:'danger',primary:false}]}
 function connectionText(){return w.navigator.onLine?'オンライン':'⚠️ オフライン保存中（接続後もこの端末のデータは保持されます）'}
 function updateConnectionStatus(){const el=$('#connection-status');if(!el)return;el.textContent=connectionText();el.classList.toggle('is-offline',!w.navigator.onLine);el.classList.toggle('is-online',w.navigator.onLine)}
 const views={punch:()=>{const sid=selectedPunchStaff||state.staff[0]?.id||'';const last=latestPunchFor(sid);const status=punchStatus(sid);const statusLabel=status==='off'?'未出勤':status==='break'?'休憩中':'出勤中';return `<section class="card hero"><p class="eyebrow">スタッフ</p><h1>${esc(state.store.name)}</h1><p>本人の打刻操作だけを表示しています。給与情報にはアクセスできません。</p></section><section class="card"><h2>スタッフを選択</h2><select id="punch-staff">${state.staff.map(s=>`<option value="${s.id}" ${s.id===sid?'selected':''}>${esc(s.name)}</option>`).join('')}</select><div class="punch-current"><span>現在の状態</span><b>${statusLabel}</b></div><div class="punch-actions punch-actions--guided" style="margin-top:12px">${punchOptions(sid).map(x=>`<button class="btn btn-${x.tone} ${x.primary?'is-next':''}" data-punch="${x.type}">${x.label}</button>`).join('')}</div><p class="punch-help">現在の状態に合わせて、次に必要な操作だけを表示しています。</p></section><section class="card"><div class="status-line"><h2>本日の勤務状況</h2><span class="status-pill">1分単位</span></div>${last?`<div class="latest-punch"><b>最新：${esc(last.type)} ${esc(last.time)}</b><small>給与計算対象：${esc(last.time)}（1分単位）</small></div>`:''}${state.punches.slice(-8).reverse().map(p=>`<p>${esc(name(p.staff))}　<b>${p.type}</b> ${p.time} <small class="calc-time">給与計算 ${p.time}</small></p>`).join('')||'<p>まだ打刻はありません。</p>'}</section>`},
 dashboard:()=>state.role==='manager'? `<section class="card hero"><p class="eyebrow">オーナー・店長</p><h1>店舗管理</h1><p>給与を表示せず、スタッフと勤怠を安全に管理します。</p></section><section class="grid"><div class="card metric"><small>スタッフ</small><b>${state.staff.length}名（無制限）</b></div><div class="card metric"><small>店舗ライセンス</small><b>1店舗</b></div></section><section class="card manager-sections"><h2>管理メニュー</h2><p>必要な項目だけ開いて操作できます。</p><details open><summary>スタッフ・勤怠</summary><div class="quick-grid"><button class="btn" data-quick-page="staff">スタッフ管理</button><button class="btn" data-quick-page="attendance">勤怠</button><button class="btn" data-quick-page="correction">打刻修正</button></div></details><details><summary>勤務ルール・交通費</summary><div class="quick-grid"><button class="btn" data-quick-page="workSettings">勤務時間・手当</button><button class="btn" data-quick-page="transport">交通費</button></div></details><details><summary>店舗・端末・出力</summary><div class="quick-grid"><button class="btn" data-quick-page="storeSettings">店舗設定</button><button class="btn" data-quick-page="devices">端末管理</button><button class="btn" data-quick-page="export">勤怠出力</button></div></details></section>`:`<section class="card hero"><p class="eyebrow">給与管理</p><h1>給与管理ダッシュボード</h1><p>全スタッフの勤怠・給与を確認します。</p></section><section class="grid"><div class="card metric"><small>スタッフ</small><b>${state.staff.length}名（無制限）</b></div><div class="card metric"><small>店舗ライセンス</small><b>1店舗</b></div></section>`,
 staff:()=>`<section class="card"><div class="row"><div><h1>スタッフ管理</h1><p>登録人数に上限はありません。</p></div><button class="btn btn-primary" id="add-staff">スタッフ登録</button></div>${state.staff.map(s=>`<div class="metric row"><b>${esc(s.name)}</b><button class="btn" data-staff="${s.id}">編集</button></div>`).join('')}</section>`,
 attendance:()=>`<section class="card"><div class="row"><div><h1>月間勤怠</h1><p>2026年9月</p></div>${state.role==='manager'?'<button class="btn btn-primary" id="add-att">勤怠追加</button>':''}</div><div class="desktop-table table-wrap"><table><thead><tr><th>日付</th><th>スタッフ名</th><th>勤務時間</th><th>休憩</th><th>実働</th><th>残業</th><th>早朝</th><th>深夜</th><th>交通費</th></tr></thead><tbody>${state.attendance.map(a=>{const s=state.staff.find(x=>x.id===a.staff)||{},x=attendanceDetail(a,state.store);return`<tr><td>${a.date}</td><td>${esc(name(a.staff))}</td><td>${a.start}–${a.end}</td><td>${a.breakMin}分</td><td>${hours(x.work)}</td><td>${hours(x.overtime)}</td><td>${hours(x.early)}</td><td>${hours(x.night)}</td><td>${yen(fare(a,s))}</td></tr>`}).join('')}</tbody></table></div></section><div class="mobile-list">${attendanceCards(state.role==='manager')}</div>`,
 workSettings:()=>`<section class="card"><h1>勤務時間・手当設定</h1><p>打刻は1分単位、残業は実働8時間超で計算します。</p><form id="work-form" class="form-grid"><label>早朝開始<input name="earlyStart" type="time" step="60" value="${state.store.earlyStart}"></label><label>早朝終了<input name="earlyEnd" type="time" step="60" value="${state.store.earlyEnd}"></label><label>早朝手当（＋円／時）<input name="earlyHourlyAdd" type="number" min="0" step="1" value="${Number(state.store.earlyHourlyAdd)||0}"></label><label>深夜開始<input name="nightStart" type="time" step="60" value="${state.store.nightStart}"></label><label>深夜終了<input name="nightEnd" type="time" step="60" value="${state.store.nightEnd}"></label><button class="btn btn-primary">設定を保存</button></form><p class="notice">日跨ぎ勤務・休憩なし勤務に対応しています。</p></section>`,
 correction:()=>`<section class="card"><div class="row"><div><h1>打刻修正</h1><p>勤怠を1分単位で追加・修正できます。</p></div><button class="btn btn-primary" id="add-att">勤怠追加</button></div></section><div class="mobile-list" style="display:grid">${attendanceCards(true)}</div>`,
 devices:()=>`<section class="card"><h1>端末管理</h1><p class="notice">1店舗1ライセンスの端末枠です。</p><div class="setting-list"><div class="metric row"><b>スタッフ端末</b><span>${state.devices.punch}/1台</span></div><div class="metric row"><b>オーナー・店長端末</b><span>${state.devices.manager}/2台</span></div><div class="metric row"><b>給与管理端末</b><span>${state.devices.accounting}/1台</span></div></div></section>`,
 storeSettings:()=>`<section class="card"><h1>店舗設定</h1><form id="store-form" class="form-grid"><label>店舗名<input name="name" required value="${esc(state.store.name)}"></label><label>管理者PIN<input name="adminPin" inputmode="numeric" pattern="[0-9]{4,8}" minlength="4" maxlength="8" required value="${esc(state.store.adminPin||'1234')}"><small>4〜8桁の数字。デモ初期値は1234です。</small></label><label>ライセンス<input disabled value="Standard／1店舗"></label><button class="btn btn-primary">店舗設定を保存</button></form></section><section class="card"><h2>デモデータ</h2><p>端末に保存されている変更内容を消して、最新の初期デモデータに戻します。</p><button type="button" class="btn btn-dark" id="reset-demo">デモデータを初期状態に戻す</button></section>`,
 paySettings:()=>`<section class="card"><h1>給与設定</h1><p>給与は時給制のみです。スタッフごとに基本時給と各手当を設定します。</p>${state.staff.map(s=>`<div class="metric row"><div><b>${esc(s.name)}</b><small>基本時給 ${yen(s.rate)}</small></div><button class="btn" data-pay="${s.id}">設定</button></div>`).join('')}</section>`,
 slips:()=>`<section class="card"><div class="row"><div><h1>給与明細</h1><p>A4形式の給与明細を表示し、PDF保存または印刷できます。</p></div><button class="btn btn-dark" id="four-up-print">4人ずつPDF／印刷</button></div></section><div class="pay-list">${state.staff.map(s=>payCard(s)).join('')}</div>`,
 transport:()=>`<section class="card"><h1>交通費設定</h1><p class="notice">日別交通費がある日は通常交通費より優先します。「¥0」と未設定は別に保存します。</p>${state.staff.map(s=>`<div class="metric row"><div><b>${esc(s.name)}</b><small>通常交通費：${s.transport===null?'未設定':yen(s.transport)}</small></div><button class="btn" data-staff="${s.id}">設定</button></div>`).join('')}</section>`,
 payroll:()=>`<section class="card hero no-print"><p class="eyebrow">PAYROLL</p><div class="row"><div><h1>給与・明細</h1><p>各割増は重複時間も項目ごとに根拠を表示します。</p></div><button class="btn" id="payroll-print">給与一覧PDF／印刷</button></div></section><section class="card payroll-print"><header class="payroll-print__head"><div><b class="print-logo">YUTORU</b><p>${esc(state.store.name)}</p></div><div><h1>給与一覧</h1><p>対象期間：2026年9月1日〜9月30日</p></div></header><div class="table-wrap"><table class="payroll-table"><thead><tr><th>スタッフ名</th><th>基本給与</th><th>残業手当</th><th>早朝手当</th><th>深夜手当</th><th>その他手当</th><th>交通費</th><th>支給合計</th></tr></thead><tbody>${state.staff.map(s=>{const p=calculatePayroll(s,state.attendance,state.store);return`<tr><th scope="row">${esc(s.name)}</th><td>${yen(p.base)}</td><td>${yen(p.otPay)}</td><td>${yen(p.nightPay)}</td><td>${yen(p.other)}</td><td>${yen(p.transport)}</td><td><b>${yen(p.total)}</b></td></tr>`}).join('')}</tbody></table></div></section><div class="pay-list no-print">${state.staff.map(s=>payCard(s)).join('')}</div>`,
 history:()=>`<section class="card"><h1>給与履歴</h1><p>確定時点の設定と計算結果をスナップショット保存します。</p>${state.history.map(h=>`<article class="metric row"><div><small>${h.period}</small><b>${esc(h.staffName)}</b></div><b>${yen(h.result.total)}</b><button class="btn" data-history="${h.id}">明細</button></article>`).join('')||'<p>給与明細を確定すると履歴に保存されます。</p>'}</section>`,
 export:()=>`<section class="card"><h1>勤怠出力</h1><p>スマートフォンからCSV保存・PDF印刷を利用できます。</p><div class="actions"><button class="btn btn-primary" id="csv">CSV出力</button><button class="btn btn-dark" id="attendance-print">PDF／印刷表示</button></div></section>`};
 function payCard(s){const p=calculatePayroll(s,state.attendance,state.store);return`<article class="card pay-card"><div class="row"><h2>${esc(s.name)}</h2><b class="total">${yen(p.total)}</b></div><dl><div><dt>基本給与</dt><dd>${yen(p.base)}</dd></div><div><dt>残業手当</dt><dd>${yen(p.otPay)}</dd></div><div><dt>早朝手当</dt><dd>${yen(p.earlyPay)}</dd></div><div><dt>深夜手当</dt><dd>${yen(p.nightPay)}</dd></div><div><dt>その他手当</dt><dd>${yen(p.other)}</dd></div><div><dt>交通費</dt><dd>${yen(p.transport)}</dd></div></dl><div class="actions"><button class="btn" data-pay="${s.id}">給与設定</button><button class="btn btn-primary" data-slip="${s.id}">給与明細を見る</button></div></article>`}
 function render(){const r=route();if(!r)return;$('#role-switch').value=r.role;$('#nav').innerHTML=NAV[r.role].map(([p,n])=>`<button data-page="${p}" class="${p===r.page?'active':''}">${n}</button>`).join('');$('#app').innerHTML=views[r.page]();bind()}
 function open(html){$('#modal-content').innerHTML=html;$('#modal').showModal()}function closeButtons(){qsa('[data-close]').forEach(b=>b.onclick=()=>$('#modal').close())}
 function staffForm(id){const current=state.staff.find(s=>s.id===id)||{id:'s'+Date.now(),name:'',rate:1200,overtimeRate:.25,earlyRate:.25,nightRate:.25,transport:null,other:0};open(`<h2>${id?'スタッフ・交通費編集':'スタッフ登録'}</h2><form id="staff-form" class="form-grid"><label>氏名<input name="name" required value="${esc(current.name)}"></label>${state.role==='manager'?`<label>通常交通費（空欄＝未設定）<input name="transport" type="number" min="0" value="${current.transport??''}"></label>`:''}<div class="actions"><button class="btn btn-primary">保存</button><button type="button" class="btn" data-close>閉じる</button></div></form>`);$('#staff-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);current.name=f.get('name');if(state.role==='manager')current.transport=f.get('transport')===''?null:Number(f.get('transport'));if(!id)state.staff.push(current);save();$('#modal').close();render()};closeButtons()}
 function attendanceForm(id){if(state.role!=='manager')return;const a=state.attendance.find(x=>x.id===id)||{id:Date.now(),staff:state.staff[0]?.id,date:'2026-09-11',start:'09:00',end:'18:00',breakMin:60,transport:null};open(`<h2>勤怠${id?'修正':'追加'}</h2><form id="att-form" class="form-grid"><label>スタッフ<select name="staff">${state.staff.map(s=>`<option value="${s.id}" ${s.id===a.staff?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label>日付<input name="date" type="date" value="${a.date}"></label><label>出勤<input name="start" type="time" step="60" value="${a.start}"></label><label>退勤<input name="end" type="time" step="60" value="${a.end}"></label><label>休憩（分）<input name="breakMin" type="number" min="0" value="${a.breakMin}"></label><label>日別交通費（空欄＝未設定）<input name="transport" type="number" min="0" value="${a.transport??''}"></label><div class="actions"><button class="btn btn-primary">保存</button><button type="button" class="btn" data-close>閉じる</button></div></form>`);$('#att-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);Object.assign(a,{staff:f.get('staff'),date:f.get('date'),start:f.get('start'),end:f.get('end'),breakMin:Number(f.get('breakMin')),transport:f.get('transport')===''?null:Number(f.get('transport'))});if(!id)state.attendance.push(a);save();$('#modal').close();render()};closeButtons()}
 function payForm(id){if(state.role!=='accounting')return;const s=state.staff.find(x=>x.id===id);open(`<h2>給与設定｜${esc(s.name)}</h2><form id="pay-form" class="form-grid"><label>基本時給<input name="rate" type="number" min="0" value="${s.rate}"></label><label>残業割増率（%）<input name="ot" type="number" value="${s.overtimeRate*100}"></label><label>深夜割増率（%）<input name="night" type="number" value="${s.nightRate*100}"></label><label>通常交通費（空欄＝未設定）<input name="transport" type="number" min="0" value="${s.transport??''}"></label><label>その他手当<input name="other" type="number" min="0" value="${s.other}"></label><div class="actions"><button class="btn btn-primary">保存</button><button type="button" class="btn" data-close>閉じる</button></div></form>`);$('#pay-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);Object.assign(s,{rate:Number(f.get('rate')),overtimeRate:Number(f.get('ot'))/100,nightRate:Number(f.get('night'))/100,transport:f.get('transport')===''?null:Number(f.get('transport')),other:Number(f.get('other'))});save();$('#modal').close();render()};closeButtons()}
 function slip(s,p,record=true){if(state.role!=='accounting')return;if(record){const snap=snapshot('2026-09',s,p);const i=state.history.findIndex(x=>x.id===snap.id);if(i<0)state.history.unshift(snap);save()}const content=`${printHead('給与明細書')}<p class="slip-staff"><span>スタッフ名</span><strong>${esc(s.name)} 様</strong></p><dl class="slip-details"><div><dt>基本時給</dt><dd>${yen(s.rate)}</dd></div><div><dt>実働時間</dt><dd>${hours(p.work)}</dd></div><div><dt>基本給与</dt><dd>${yen(p.base)}</dd></div><div><dt>残業時間／残業手当</dt><dd>${hours(p.overtime)}／${yen(p.otPay)}</dd></div><div><dt>早朝時間／早朝手当</dt><dd>${hours(p.early)}／${yen(p.earlyPay)}</dd></div><div><dt>深夜時間／深夜手当</dt><dd>${hours(p.night)}／${yen(p.nightPay)}</dd></div><div><dt>その他手当</dt><dd>${yen(p.other)}</dd></div><div><dt>交通費</dt><dd>${yen(p.transport)}</dd></div><div class="slip-total"><dt>支給合計</dt><dd>${yen(p.total)}</dd></div></dl>`;open(`<article class="print-sheet">${content}</article><div class="actions no-print"><button class="btn btn-dark" id="print-slip">PDF保存／印刷</button><button class="btn" data-close>閉じる</button></div>`);$('#print-slip').onclick=()=>openPrintPage(`${s.name} 給与明細書`,content);closeButtons()}
 function bind(){const workForm=$('#work-form');if(workForm)workForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);Object.assign(state.store,{earlyStart:f.get('earlyStart'),earlyEnd:f.get('earlyEnd'),earlyHourlyAdd:Number(f.get('earlyHourlyAdd'))||0,nightStart:f.get('nightStart'),nightEnd:f.get('nightEnd')});save();render()};const storeForm=$('#store-form');if(storeForm)storeForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.store.name=f.get('name');state.store.adminPin=f.get('adminPin')||'1234';save();render()};qsa('#nav [data-page]').forEach(b=>b.onclick=()=>{w.location.hash='#/'+state.role+'/'+b.dataset.page});qsa('[data-quick-page]').forEach(b=>b.onclick=()=>{w.location.hash='#/'+state.role+'/'+b.dataset.quickPage});const punchStaff=$('#punch-staff');if(punchStaff)punchStaff.onchange=e=>{selectedPunchStaff=e.target.value;render()};qsa('[data-punch]').forEach(b=>b.onclick=()=>{const staffId=$('#punch-staff')?.value||selectedPunchStaff;selectedPunchStaff=staffId;state.punches.push({staff:staffId,type:b.dataset.punch,time:new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})});save();render()});$('#add-staff')?.addEventListener('click',()=>staffForm());$('#add-att')?.addEventListener('click',()=>attendanceForm());qsa('[data-att]').forEach(b=>b.onclick=()=>attendanceForm(Number(b.dataset.att)));qsa('[data-staff]').forEach(b=>b.onclick=()=>staffForm(b.dataset.staff));qsa('[data-pay]').forEach(b=>b.onclick=()=>payForm(b.dataset.pay));qsa('[data-slip]').forEach(b=>b.onclick=()=>{const s=state.staff.find(x=>x.id===b.dataset.slip);slip(s,calculatePayroll(s,state.attendance,state.store))});qsa('[data-history]').forEach(b=>b.onclick=()=>{const h=state.history.find(x=>x.id===b.dataset.history),s={...h.settings,name:h.staffName};slip(s,h.result,false)});$('#four-up-print')?.addEventListener('click',openFourUpPrintPage);$('#payroll-print')?.addEventListener('click',()=>openPrintPage('給与一覧',payrollPrintContent()));$('#csv')?.addEventListener('click',()=>download(csv(state),'YUTORU_Standard_勤怠.csv','text/csv'));$('#attendance-print')?.addEventListener('click',()=>openPrintPage('勤怠一覧',attendancePrintContent()))};$('#reset-demo')?.addEventListener('click',()=>{if(!w.confirm('デモデータを初期状態に戻します。端末内で変更したデモ内容は消えます。よろしいですか？'))return;const role=state.role;w.localStorage.removeItem(STORAGE_KEY);state=seed();state.role=role;selectedPunchStaff=state.staff[0]?.id||'';save();w.alert('デモデータを最新の初期状態に戻しました。');w.location.reload()})
 function download(data,name,type){const a=d.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
 qsa('[data-role]').forEach(b=>b.onclick=()=>requestRole(b.dataset.role));$('#role-switch').onchange=e=>{const requested=e.target.value;e.target.value=state.role||'punch';requestRole(requested)};w.addEventListener('hashchange',render);w.addEventListener('online',updateConnectionStatus);w.addEventListener('offline',updateConnectionStatus);updateConnectionStatus()}
return{STORAGE_KEY,ACCESS,seed,attendanceDetail,fare,calculatePayroll,authorize,requiresPin,verifyPin,snapshot,csv,boot};});
