const assert=require('node:assert/strict');
const fs=require('node:fs');
const crypto=require('node:crypto');
const core=require('../standard/standard.js');
const html=fs.readFileSync('standard/index.html','utf8');
const css=fs.readFileSync('standard/standard.css','utf8');
const js=fs.readFileSync('standard/standard.js','utf8');
const vercel=JSON.parse(fs.readFileSync('standard/vercel.json','utf8'));
assert.equal(crypto.createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),'b0960f38872dbd1fe02c1cf56ab5fb52a70097f1aa023bccbd9d72d061124628','Light版が変更されています');
assert.match(html,/Standard DEMO/);assert.match(html,/standard\.js/);
assert.equal(core.STORAGE_KEY,'yutoru_standard_app_v1');assert.doesNotMatch(core.STORAGE_KEY,/light/i);
assert.equal(vercel.cleanUrls,true);assert.equal(vercel.trailingSlash,false);
assert.deepEqual(core.ACCESS.punch,['punch']);
assert.ok(!core.authorize('punch','payroll'));assert.ok(!core.authorize('manager','payroll'));assert.ok(core.authorize('accounting','payroll'));assert.ok(core.authorize('accounting','history'));
const state=core.seed();for(let i=0;i<1000;i++)state.staff.push({id:'x'+i,name:'x'});assert.equal(state.staff.length,1004,'人数上限なし');
for(const [staffCount,pageCount] of [[1,1],[4,1],[5,2],[8,2],[9,3]]){const staff=Array.from({length:staffCount},(_,i)=>i);const pages=core.groupsOfFour(staff);assert.equal(pages.length,pageCount,`${staffCount}人のページ数が不正です`);assert.ok(pages.every(page=>page.length<=4),'1ページが4人を超えています');assert.deepEqual(pages.flat(),staff,'スタッフの並びまたは人数が変わっています')}
const normal=core.attendanceDetail({start:'09:00',end:'18:00',breakMin:60});assert.equal(normal.work,480);assert.equal(normal.overtime,0);
const noBreak=core.attendanceDetail({start:'09:00',end:'19:00',breakMin:0});assert.equal(noBreak.work,600);assert.equal(noBreak.overtime,120);
const overnight=core.attendanceDetail({start:'22:00',end:'06:00',breakMin:0});assert.equal(overnight.work,480);assert.equal(overnight.night,420);assert.equal(overnight.early,60);
const s={id:'a',name:'A',rate:1000,overtimeRate:.25,earlyRate:.25,nightRate:.25,transport:500,other:100};
assert.equal(core.fare({transport:null},s),500);assert.equal(core.fare({transport:0},s),0);assert.equal(core.fare({transport:800},s),800);
const pay=core.calculatePayroll(s,[{staff:'a',start:'05:00',end:'14:00',breakMin:0,transport:0}]);
assert.equal(pay.work,540);assert.equal(pay.overtime,60);assert.equal(pay.early,180);assert.equal(pay.base,9000);assert.equal(pay.otPay,250);assert.equal(pay.earlyPay,750);assert.equal(pay.transport,0);assert.equal(pay.total,10100);
const snap=core.snapshot('2026-09',s,pay);s.rate=9999;assert.equal(snap.settings.rate,1000);assert.equal(snap.result.total,10100);
const output=core.csv({staff:[s],attendance:[{staff:'a',date:'2026-09-01',start:'09:00',end:'18:00',breakMin:60,transport:0}]});assert.match(output,/日付,スタッフ名/);assert.match(output,/2026-09-01,A/);
assert.match(css,/\.mobile-list\{display:grid/);assert.match(css,/@page\{size:A4 portrait/);assert.match(css,/body\.printing>#?\*:not|body\.printing>\*:not/);assert.match(css,/\.nav\{[^}]*overflow-x:auto/);
for(const label of ['基本給与','残業手当','早朝手当','深夜手当','その他手当','交通費','支給合計','給与設定','給与明細を見る'])assert.match(fs.readFileSync('standard/standard.js','utf8'),new RegExp(label));
for(const label of ['スタッフ名','基本給与','残業手当','深夜手当','その他手当','交通費','支給合計'])assert.match(js,new RegExp(`<th>${label}</th>`),'給与一覧PDFの列が不足しています');
for(const label of ['基本時給','実働時間','基本給与','残業時間／残業手当','深夜時間／深夜手当','その他手当','交通費','支給合計'])assert.match(js,new RegExp(`<dt>${label}</dt>`),'給与明細PDFの項目が不足しています');
assert.match(js,/class="print-logo">YUTORU</);assert.match(js,/id="payroll-print"/);
assert.match(js,/w\.open\('','_blank'\)/,'印刷専用ページを新しい画面で開いていません');
assert.match(js,/page\.document\.write\(printDocument/,'印刷専用HTMLを書き込んでいません');
assert.match(js,/ポップアップを許可して/,'ポップアップブロック時の案内がありません');
assert.match(js,/共有ボタンから“プリント”または“ファイルに保存”/,'iPhone向けの案内がありません');
assert.match(js,/@media print\{/);assert.match(js,/\.guide\{display:none\}/,'印刷時に案内が非表示になりません');
assert.doesNotMatch(js,/w\.print\(/,'元画面からwindow.print()を呼び出しています');
assert.match(js,/openPrintPage\('給与一覧',payrollPrintContent\(\)\)/);
assert.match(js,/id="four-up-print">4人ずつPDF \/ 印刷</);
assert.match(js,/openPrintPage\('給与明細書（4人ずつ）',fourUpPrintContent\(\)\)/,'4人分専用ページを新しいタブで開いていません');
assert.match(js,/\.four-up-page\{display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\);grid-template-rows:repeat\(2,minmax\(0,1fr\)\)/,'2×2配置ではありません');
assert.match(js,/\.four-up-page\{[^}]*break-after:page;page-break-after:always/,'4人ごとの改ページ指定がありません');
assert.match(js,/\.four-up-slip\{[^}]*break-inside:avoid;page-break-inside:avoid/,'明細の分割防止指定がありません');
for(const label of ['基本時給','実働時間','基本給与','残業時間 / 残業手当','深夜時間 / 深夜手当','その他手当','交通費','支給合計'])assert.match(js,new RegExp(label.replace('/','\\/')),'4人ずつ給与明細の項目が不足しています');
assert.match(js,/openPrintPage\('勤怠一覧',attendancePrintContent\(\)\)/);
assert.match(css,/\.payroll-table thead\{display:table-header-group\}/);assert.match(css,/\.payroll-table tr\{[^}]*break-inside:avoid/);assert.match(css,/\.print-sheet\{[^}]*break-inside:avoid/);
console.log('standard-demo tests: ok');
