const assert=require('node:assert/strict');
const fs=require('node:fs');
const crypto=require('node:crypto');
const core=require('../standard/standard.js');
const html=fs.readFileSync('standard/index.html','utf8');
const css=fs.readFileSync('standard/standard.css','utf8');
const vercel=JSON.parse(fs.readFileSync('standard/vercel.json','utf8'));
assert.equal(crypto.createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),'b0960f38872dbd1fe02c1cf56ab5fb52a70097f1aa023bccbd9d72d061124628','Light版が変更されています');
assert.match(html,/Standard DEMO/);assert.match(html,/standard\.js/);
assert.equal(core.STORAGE_KEY,'yutoru_standard_app_v1');assert.doesNotMatch(core.STORAGE_KEY,/light/i);
assert.equal(vercel.cleanUrls,true);assert.equal(vercel.trailingSlash,false);
assert.deepEqual(core.ACCESS.punch,['punch']);
assert.ok(!core.authorize('punch','payroll'));assert.ok(!core.authorize('manager','payroll'));assert.ok(core.authorize('accounting','payroll'));assert.ok(core.authorize('accounting','history'));
const state=core.seed();for(let i=0;i<1000;i++)state.staff.push({id:'x'+i,name:'x'});assert.equal(state.staff.length,1004,'人数上限なし');
const normal=core.attendanceDetail({start:'09:00',end:'18:00',breakMin:60});assert.equal(normal.work,480);assert.equal(normal.overtime,0);
const noBreak=core.attendanceDetail({start:'09:00',end:'19:00',breakMin:0});assert.equal(noBreak.work,600);assert.equal(noBreak.overtime,120);
const overnight=core.attendanceDetail({start:'22:00',end:'06:00',breakMin:0});assert.equal(overnight.work,480);assert.equal(overnight.night,420);assert.equal(overnight.early,60);
const s={id:'a',name:'A',rate:1000,overtimeRate:.25,earlyRate:.25,nightRate:.25,transport:500,other:100};
assert.equal(core.fare({transport:null},s),500);assert.equal(core.fare({transport:0},s),0);assert.equal(core.fare({transport:800},s),800);
const pay=core.calculatePayroll(s,[{staff:'a',start:'05:00',end:'14:00',breakMin:0,transport:0}]);
assert.equal(pay.work,540);assert.equal(pay.overtime,60);assert.equal(pay.early,180);assert.equal(pay.base,9000);assert.equal(pay.otPay,250);assert.equal(pay.earlyPay,750);assert.equal(pay.transport,0);assert.equal(pay.total,10100);
const snap=core.snapshot('2026-09',s,pay);s.rate=9999;assert.equal(snap.settings.rate,1000);assert.equal(snap.result.total,10100);
const output=core.csv({staff:[s],attendance:[{staff:'a',date:'2026-09-01',start:'09:00',end:'18:00',breakMin:60,transport:0}]});assert.match(output,/日付,スタッフ名/);assert.match(output,/2026-09-01,A/);
assert.match(css,/\.mobile-list\{display:grid/);assert.match(css,/@page\{size:A4 portrait/);assert.match(css,/body\.printing>#?\*:not|body\.printing>\*:not/);assert.match(css,/\.nav\{[^}]*overflow-x:auto/);
for(const label of ['基本給与','残業手当','早朝手当','深夜手当','その他手当','交通費','支給合計','給与設定','給与明細を見る'])assert.match(fs.readFileSync('standard/standard.js','utf8'),new RegExp(label));
console.log('standard-demo tests: ok');
